version: 2
jobs:
  lint-react-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Linting React
          command: |
            npm i
            npm run lint
      - save_cache:
          paths: 
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}

  build-react-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Building React App
          command: |
            npm run build
  build:
    docker:
    # Use the same Docker base as the project
      - image: circleci/node:13.8.0

    working_directory: ~/repo

    steps:
      - checkout    
      - run:
          name: install hadolint
          command: |            
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                sudo chmod +x /bin/hadolint
      
      # run lint!
      - run:
          name: run lint
          command: |            
            hadolint Dockerfile
  workflows:
    default:
      jobs:
        - lint-react-app
        - build-react-app:
            requires: [lint-react-app]
        - build:
            requires: [build-react-app]