version: 2
jobs:
  build:
    docker:
    # Use the same Docker base as the project
      - image: circleci/node:10.16.3

    working_directory: ~/repo

    steps:
      - checkout    
      - run:
          name: install hadolint
          command: |            
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                sudo chmod +x /bin/hadolint
      
      # run lint!
      - run:
          name: run lint
          command: |            
            hadolint Dockerfile 